# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7e509579-2797-421f-a96e-2a2bd4a1f84f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7e509579-2797-421f-a96e-2a2bd4a1f84f".device = "/dev/disk/by-uuid/7e509579-2797-421f-a96e-2a2bd4a1f84f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5AC4-F27F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d6cb3072-f3da-4b47-a455-382c0714840c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d6cb3072-f3da-4b47-a455-382c0714840c".device = "/dev/disk/by-uuid/d6cb3072-f3da-4b47-a455-382c0714840c";

  swapDevices =
    [ { device = "/dev/mapper/luks-fbae94df-af2a-4f7a-9d1d-1fcfeef04583"; }
    ];

  boot.initrd.luks.devices."luks-fbae94df-af2a-4f7a-9d1d-1fcfeef04583".device = "/dev/disk/by-uuid/fbae94df-af2a-4f7a-9d1d-1fcfeef04583";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
